### ISSUE TITLE
Implementation of 'make primary' functionality for icons

### ISSUE THREAD

**Issue by ainsliebeattie** [transitionnetwork/TNv3.0#45] opened 2016-10-24 07:31 UTC
There is an issue with the icon implementation:  example - we have listed food as the primary icon for Crystal palace food story and we have listed culture as a secondary one. It comes up as culture first and it doesn't show the other listings.  This is working as correct functionality. It would be good to see visually the other icons, as well has having them list appropriately with their primary one highlighted.
<img width="1295" alt="screen shot 2016-10-24 at 8 29 02 am" src="https://cloud.githubusercontent.com/assets/22507393/19636938/3160bd10-99c4-11e6-9bb8-4080fa4117b4.png">

**Comment by yvonnestruthers** [comment] 2016-10-24 09:26
Hi @ainsliebeattie I can't find this story to have a look at what has been ticked etc - the only story I can find about Crystal Palace food doesn't have anything ticked. I have looked at this one as an example: http://transitionmovement.org/news-and-blog/book-review-and-competition-born-on-third-base-by-chuck-collins/

The functionality on the icons which has been agreed and implemented is as follows: 
- List of topics agreed and icons created for each taxonomy
- Icon to show in listing for article and next to heading when you click in to the article
- Icons to click through to the topic landing page 
- Article to be listed on topic landing page for relevant topics it has been listed for 

This is all in place and working as agreed. 

The functionality you've described around having additional icons and topics listed isn't included in the current scope. If you'd like the secondary icons/topics to show in some way that is possible, but that is additional to what has been previously discussed and so some additional design work would need to be undertaken to think through how this should be done. We'd also need to agree a limit to the number of icons it is possible to add, as there is only a finite amount of space in the article listing box for the icons to fit in there. 

Please could you list out the additional functionality you require for the icons/topics and we can estimate on that for you.

**Comment by samuk** [comment] 2016-10-25 11:55
Hi Ella

This is the one Ainslie was referring to:

http://transitionmovement.org/wp-admin/post.php?post=6946&action=edit

http://transitionmovement.org/stories/crystal-palace-food-market/

It's a 'story' content type rather than a news item. The primary topic is 'Food & Drink' but the culture & society icon is displayed.

Thanks

Sam

**Comment by yvonnestruthers** [comment] 2016-10-25 14:03
Hi Sam,

Thanks for sharing this example, I can see what you mean now, so that's helpful. 

As I said on my previous comment, the use of the icons/topics was only ever discussed and scoped to use 1 topic (and therefore 1 icon). So the addition of more than one topic is an additional requirment which isn't catered for at the moment. Out of the box, Wordpress will allow you to tick more than one topic (and it's actually quite fiddly to limit the tick boxes to only let people tick one topic only inthe CMS), however because we had only discussed the use of one icon this wasn't an issue. 

As you are actually wanting to tick more than one topic per story/post, and to choose a 'primary' topic (which will be the icon displayed) we need to amend the functionality from how it was scoped to allow this. The amend will be to pull the topic selected as 'primary' through into the front end, and serve the icon for that primary topic. It will need some additional time from Tom to do this - he thinks around 30 minutes. We will not charge you on this occasion for this piece of additional work. 

If you wish for additional icons/topics to appear in the front end, this would need to be estimated separately as that's a much larger piece of work.

**Comment by yvonnestruthers** [comment] 2016-10-25 14:05
@arhinostorm please could you implement the following: 

where there is more than one topic ticked, the icon relating to the topic selected as 'primary' should be served (at the moment the first one alphabetically is served). 

Thanks!

**Comment by yvonnestruthers** [comment] 2016-11-01 11:18
The functionality I described above (ability to select 'make primary' icon to appear) has been implemented. 

However, doing this does open a bit of a 'can of worms': 

You can pick several topics for a story, news article etc, and make one primary. The primary one is the one that displays on that story... currently all posts, stories etc are displaying just ONE topic. When you filter stories by topic this makes it confusing. I might pick 'art' from the dropdown and see 'culture & society' in the results (behind the scenes this story is tagged with both with culture and society being the primary). If you have a play filtering stories it almost feels broken because of it.

So the issue is that the designs are only using one topic (because this was the original requirement), and you are using multiple. We can display multiple BUT this will need to be properly thought out from a design perspective, as there's just not that much space. Showing all the topics on say the stories homepage will work fine, but on the news page and others like it it'll ruin the layout so they will need to be redesigned. 

I'm going to close this issue for now, as we have achieved what we can with the scope and designs that we have, but I am adding this to our list as something to be addressed as part of phase 2. If you want to avoid the potholes in the mean time, you will need to revert to using just one topic per item.

**Closed as completed by yvonnestruthers** 2016-11-01 11:18 UTC
Labels: enhancement, Ready for Tom
