### ISSUE TITLE
Training testimonials page not working

### ISSUE THREAD

**Issue by ainsliebeattie** [transitionnetwork/TNv3.0#47] opened 2016-10-24 07:37 UTC
See screenshot - functionality not working correctly.
<img width="646" alt="screen shot 2016-10-24 at 8 36 39 am" src="https://cloud.githubusercontent.com/assets/22507393/19637089/120e9c74-99c5-11e6-95be-2914381d02e0.png">

**Comment by arhinostorm** [comment] 2016-10-24 08:50
This looks like something that's been done using the recently added masonry grid flexible content block? The top row is the expected behaviour of the template (the top three items). 

The second row has been manually added, and photos have been set to link to themselves? What is the expected functionality here?

**Comment by yvonnestruthers** [comment] 2016-10-24 09:50
This looks like an input issue rather than anything built not working - I'm going to close this issue for now. 

If I have misunderstood the issue please let me know more details and we can address. 

Thanks

**Closed as completed by yvonnestruthers** 2016-10-24 09:50 UTC
